site_name: Joe O'Regan | Project Portfolio
docs_dir: docs
site_dir: site

copyright: Copyright &copy; 2026 Joe O'Regan

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joeaoregan/
    - icon: fontawesome/brands/github
      link: https://github.com/joeaoregan
    - icon: material/certificate
      link: https://www.credly.com/users/joe-o-regan
    - icon: simple/githubpages
      link: https://joeaoregan.github.io/
    - icon: simple/artstation
      link: https://www.artstation.com/joeaoregan
    - icon: simple/sketchfab
      link: https://www.sketchfab.com/joeoregan      

theme:
  name: material  
  favicon: images/favicon.ico
  icon:
    admonition:
      note: material/alpha-j
      success: material/alpha-j
      warning: material/alpha-j
      danger: material/alpha-j
  logo: images/logo.png
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.top
    - content.code.copy

nav:
  - Home: 
    - Home: index.md
    - External Links:    
      - Linkedin: https://www.linkedin.com/in/joeaoregan/
      - GitHub: https://github.com/joeaoregan
  - 2026 TUS: college/2026-tus/index.md
  - College: 
    - Courses: college/index.md
    - 2026 TUS: college/2026-tus/index.md
    - 2023 DKIT: college/2023-dkit/index.md
    - 2021 LIT: college/2021-lit/index.md
    - 2018 AIT: college/2018-ait/index.md
    - 2018 LIT:
      - LIT: college/2018-lit/index.md
      - 4th Year: college/2018-lit/year4.md
      - 3rd Year: college/2018-lit/year3.md
      - 2nd Year: college/2018-lit/year2.md
  - Projects: projects/index.md
  - Games: 
    - Overview: games/index.md
    - Zombie Apocalypse: games/zombie-apocalypse.md
    - Antibody: games/antibody.md
  - 3D Models: 3d-models/index.md
  - Certificates: certification/index.md
  
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - college/*
              - projects/*
              - games/*

repo_url: https://github.com/joeaoregan
repo_name: GitHub

site_url: https://joeaoregan.github.io/